### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by wujastyk** [chchch/quick-palaeographer#2]
Would it be possible for QP to allow greater magnification of the folio images?  I notice that enlargement hits a limit, maybe the inherent pixel size of the image?  And if I load the same image into [Pix](https://github.com/linuxmint/pix) (a Linux viewer) I can blow the images up quite a lot more before pixellation makes it pointless. And that can be very helpful when squinting at akṣaras

**Comment by chchch** [comment]
I've doubled the max zoom level, let me know how it goes!

**Comment by wujastyk** [comment]
That makes all the difference! I wish I'd thought to ask earlier.  Much, much better.  Thank you!
