### ISSUE TITLE
feature request: recent files memory

### ISSUE THREAD

**Issue by wujastyk** [chchch/quick-palaeographer#3]
When you open an image file, a little window pops up asking whether you want to reload the data from a previous session on that leaf.  That's great. Would it be possible to have that window or one similar pop up _before_ you've done the "load image" selection?  Or, when the "load image" prompt appears, perhaps there could be a reminder of the last few images opened?  

What I'm finding as I work on different parts of the manuscripts, in my own work or when talking with other project members, is that I always forget the last folio we were working on.  So I have to look up the filename in my TEI transcription, and go back to the "load image" dialogue, etc.  Many programs have a "recent files" memory; so I was wondering wither qp could too.

**Comment by chchch** [comment]
Hmm, I'm actually not sure how to implement this yet. Quick Palaeographer is implemented as a "web app" that stores your data in your browser. It doesn't (shouldn't?) have access to your filesystem, for security reasons, so it shouldn't know what files on your computer you've opened before.

**Comment by wujastyk** [comment]
Ah, yes, I see.  It's fine.  I can work around this.  I should try sticky
<https://www.addictivetips.com/ubuntu-linux-tips/linux-mint-sticky-notes/>.
:-)
