### ISSUE TITLE
Feature request/query

### ISSUE THREAD

**Issue by wujastyk** [chchch/quick-palaeographer#4]
QP allows me to save character identifications from several different folios and merge them together into a single HTML file.  That's great.

Is there a way to extend this so that two different users (on different computers) who have worked on the same folio can merge their work?  

I'm looking for a way for a team to work collaboratively to produce a comprehensive chart of characters for a scribe.

**Comment by chchch** [comment]
I've made an update so that when you import a JSON file with annotations, it doesn't overwrite the existing ones. So if you open a folio with your annotations, and then import someone else's annotations on the same folio, it should get merged.

**Comment by wujastyk** [comment]
Thank you, that's perfect.  Again.
