### ISSUE TITLE
different image sizes

### ISSUE THREAD

**Issue by wujastyk** [chchch/quick-palaeographer#5]
I am appending the work of several inputters to make a single big chart of identified characters. 

I have found that the work sent by other inputters differs in size from my own:

![image](https://user-images.githubusercontent.com/762246/207141433-0dad4652-247e-407e-a2d1-6beab471659a.png)

Is there a process we can use that will normalize the sizes of the image-grabs?

**Comment by chchch** [comment]
hmm, I set the size of every image to be 100 pixels in height. Does it look better now? I imagine the small images might be pretty pixelated though... I guess those are taken from lower-resolution images? If they're the same resolution, there might be a bug in the code.

**Comment by wujastyk** [comment]
I'm still seeing the issue:
![image](https://user-images.githubusercontent.com/762246/207435027-6d797460-e7e3-4e86-a319-757a1db1849e.png)

Wait, when does the image size get set?  I was importing the same HTML files as yesterday.  If the 100 pixels gets set when saving the HTML, I should get a re-saved 113v and try again.

**Comment by wujastyk** [comment]
Tried re-saving htmls, no luck.  
Also, "save annotations" doesn't do anything...

**Comment by chchch** [comment]
Ok, I should have fixed both issues now. The size is just set on the HTML element, so it should work even with files you've already made.

**Comment by wujastyk** [comment]
Yessss!  (punches the air :-)
Thank you, Charles.

**Comment by wujastyk** [comment]
Today I had this message from Vandana, one of the transcribers on my project:

> While working on it yesterday,  unknowingly the fonts of the annotation file became very huge.I tried a lot to get them back in normal size as I can't concentrate. 

Might this be an unwanted byproduct of the 100pxl normalization?

She sent these images:
![image](https://user-images.githubusercontent.com/762246/207927382-4e1eb0fe-80a3-4c51-8c3e-69c876020ad4.png)
![20221214_121532](https://user-images.githubusercontent.com/762246/207927410-e89c70a9-8266-4c79-becc-dcc8039e2aba.jpg)

**Comment by chchch** [comment]
Hmm yes, I made everything 100 pixels high, even in the sidebar. I've changed it now so that it only normalizes the heights in the popup window, not in the sidebar.

**Comment by wujastyk** [comment]
Thank you!  
Best, Dominik
